apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd1
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/theJaxon/argocd.git
    targetRevision: main
